### ISSUE TITLE
Error searching for locality

### ISSUE THREAD

**Issue by er2de2** [bmaroti9/Overmorrow#14] opened 2024-05-19 10:52 UTC
When I search for my locality I get this error

![Screenshot_20240519-124557.png](https://github.com/bmaroti9/Overmorrow/assets/62346235/800dafd4-c8a5-4147-b505-86eedd4003ab)

**Comment by bmaroti9** [comment] 2024-05-19 11:40
Hmm, it seems like it dies when fetching for the data.
Some quick questions: does this only happen for Dobra? If you change languages does it work?
Interestingly if i search for the same place it works.

**Comment by er2de2** [comment] 2024-05-19 12:28
In my case it does not work in every language
Strange, because until this morning it was  ok.
When you search Dobra select the fourth locality

**Comment by bmaroti9** [comment] 2024-05-19 19:40
Could you check if the search provider in the settings page is set to
wearherpi?  The open-meteo search provider could be the cause as it
sometimes gives places with certain parameters missing, indicating the null
check.

**Comment by er2de2** [comment] 2024-05-20 06:29
On wearherapi it detects the location with no problem.
Yesterday strange things were happening :).
Searching for my locality on https://open-meteo.com/en/docs/geocoding-api#name=Dobra returns good results,my locality is on the fourth position.
Searching in the app returned only localities from Romania.
I reinstalled the app and now everything is ok

**Comment by bmaroti9** [comment] 2024-05-20 13:16
I don't really know what could have happened. I tried all kind of different settings but it always found the place for me. I guess it's good it's fixed, though it still could come up later... 
I would like to implement a way to report the stacktrace when this sort of thing happens, sometime in the future, to help solve these types of problems.
But I guess since it got fixed... I will go ahead and close it. :)

**Closed by bmaroti9** 2024-05-20 13:16 UTC
