### ISSUE TITLE
Bug: Can't access Weather info.

### ISSUE THREAD

**Issue by SagXD** [bmaroti9/Overmorrow#23] opened 2024-07-22 06:15 UTC
I am getting this error: general error at place 2: type 'Null' is not subtype of type 'int'

![Screenshot_20240722-114425.png](https://github.com/user-attachments/assets/c31a1aa5-492b-4b83-a708-4153a0bd5f42)

Tried both providers.

**Comment by bmaroti9** [comment] 2024-07-22 06:24
yes, i just checked and i am getting it too. it seems like weatherapi have just updated their air quality data formatting, without telling anyone that this will break all apps using it.🙄

**Comment by bmaroti9** [comment] 2024-07-22 06:34
turns out i was wrong. it seems like it just currently returns an empty list for the aqi data.
![Screenshot from 2024-07-22 08-32-40](https://github.com/user-attachments/assets/fa9ab8e6-70f5-41d4-a5cb-091e411fabfc)

i have no idea what to do about this. lets just hope they fix it soon, and then everything goes back to normal...

**Comment by bmaroti9** [comment] 2024-07-22 06:40
I have tried contacting them, that the aqi doesn't work. hope they see it and hopefully, fix it.

**Comment by bmaroti9** [comment] 2024-07-22 07:38
it's good because now the whole current data is missing.
![Screenshot from 2024-07-22 09-37-45](https://github.com/user-attachments/assets/0899ce62-1f83-410d-b7a9-6b86c4a85c3d)
i'm still waiting for their reply.

**Comment by bmaroti9** [comment] 2024-07-22 07:55
now the whole server is down... 
![Screenshot from 2024-07-22 09-54-37](https://github.com/user-attachments/assets/16cb0558-d571-4e13-ac78-cef9bc440961)

**Comment by bmaroti9** [comment] 2024-07-22 09:37
the data is back but the air quality is still missing.
still waiting for their response...

**Comment by bmaroti9** [comment] 2024-07-23 06:24
the problem is fixed. the air quality is no longer returning an empty list. all is back to normal.👍
HOWEVER, this should not have happened! One of the weather providers dying shouldn't result in the whole application dying too. This was an error on my side. I wrote the code in a way that the weatherapi air quality and sunrise/sunset data was always fetched, and next to that, either the weatherapi forecast or the open-meteo forecast. This way if there was a problem with either the weatherapi air quality or sunrise/sunset then even if you selected to use open-meteo data, it would still kill the app. 
THIS IS WHY i made the necessary changes yesterday, which totally separated the two providers, so even if next time one of them stops working the other will not be affected. This change is already in the code, and will be included in the next release.

**Closed by bmaroti9** 2024-07-23 06:24 UTC
Labels: bug
